[package]
name = "bubbler"
version = "0.1.0"
edition = "2024"

[dependencies]
egglog = { path = "egglog" }
ruler = { path = "ruler" }
symbolic_expressions = "5.0.3"

[lib]
name = "bubbler"
path = "src/lib.rs"
